/* original parser id follows */
/* yysccsid[] = "@(#)yaccpar	1.9 (Berkeley) 02/21/93" */
/* (use YYMAJOR/YYMINOR for ifdefs dependent on parser version) */

#define YYBYACC 1
#define YYMAJOR 1
#define YYMINOR 9
#define YYPATCH 20140715

#define YYEMPTY        (-1)
#define yyclearin      (yychar = YYEMPTY)
#define yyerrok        (yyerrflag = 0)
#define YYRECOVERING() (yyerrflag != 0)
#define YYENOMEM       (-2)
#define YYEOF          0
#define YYPREFIX "yy"

#define YYPURE 0

#line 4 "compiler_hw2.y"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "share.h"	/* header file generated by bison */
extern int yylineno;
extern int yylex();
extern char* yytext;   /* Get current token from lex*/
extern char buf[256];  /* Get current code line from lex*/
extern char buf2[256];  /* Get current code line from lex*/
int yerror;
/*int now_scope = 0; 
int float_flag = 0;
typedef struct symbol{
    char name[20];
    char kind[20];
    char type[10];
    int scope;
    char attribute[20];
    int func_def;
}symbol;
symbol global_table[30];
symbol symbol_table[30];
int symbolno = 0;
int globalno = 0;

Symbol table function - you can add new function if needed. 
in lookup_symbol(symbol *t,char *name,int n);
int check_funcdef(symbol *t,char *name,int n);
symbol create_symbol(char *name,char *kind,char *type,int scope,char *attribute);
void insert_symbol(symbol *t,symbol s,int i);
void dump_symbol(symbol *t,int scope,int n);*/
#line 41 "compiler_hw2.y"
#ifdef YYSTYPE
#undef  YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
#endif
#ifndef YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
typedef union {
    int i_val;
    double f_val;
    char* string;
 /*  symbol symbol;*/
} YYSTYPE;
#endif /* !YYSTYPE_IS_DECLARED */
#line 67 "y.tab.c"

/* compatibility with bison */
#ifdef YYPARSE_PARAM
/* compatibility with FreeBSD */
# ifdef YYPARSE_PARAM_TYPE
#  define YYPARSE_DECL() yyparse(YYPARSE_PARAM_TYPE YYPARSE_PARAM)
# else
#  define YYPARSE_DECL() yyparse(void *YYPARSE_PARAM)
# endif
#else
# define YYPARSE_DECL() yyparse(void)
#endif

/* Parameters sent to lex. */
#ifdef YYLEX_PARAM
# define YYLEX_DECL() yylex(void *YYLEX_PARAM)
# define YYLEX yylex(YYLEX_PARAM)
#else
# define YYLEX_DECL() yylex(void)
# define YYLEX yylex()
#endif

/* Parameters sent to yyerror. */
#ifndef YYERROR_DECL
#define YYERROR_DECL() yyerror(const char *s)
#endif
#ifndef YYERROR_CALL
#define YYERROR_CALL(msg) yyerror(msg)
#endif

extern int YYPARSE_DECL();

#define PRINT 257
#define IF 258
#define ELSE 259
#define FOR 260
#define SEMICOLON 261
#define ADD 262
#define SUB 263
#define MUL 264
#define DIV 265
#define MOD 266
#define INC 267
#define DEC 268
#define MT 269
#define LT 270
#define MTE 271
#define LTE 272
#define EQ 273
#define NE 274
#define LSB 275
#define RSB 276
#define COMMA 277
#define QUOTA 278
#define WHILE 279
#define ASGN 280
#define ADDASGN 281
#define SUBASGN 282
#define MULASGN 283
#define DIVASGN 284
#define MODASGN 285
#define AND 286
#define OR 287
#define NOT 288
#define LB 289
#define RB 290
#define LCB 291
#define RCB 292
#define TRUE 293
#define FALSE 294
#define RET 295
#define CONT 296
#define BREAK 297
#define COMMENT 298
#define I_CONST 299
#define F_CONST 300
#define BOOL 301
#define INT 302
#define STRING 303
#define FLOAT 304
#define VOID 305
#define STR_CONST 306
#define ID 307
#define SEMICOLONE 308
#define YYERRCODE 256
typedef short YYINT;
static const YYINT yylhs[] = {                           -1,
    0,    0,   27,   27,    6,    6,    6,    6,    6,    6,
    6,    5,    5,    5,    5,    5,    5,    5,   28,   28,
   16,   17,    3,   18,   18,   18,   19,   19,   21,   21,
   21,   21,   21,   21,   11,   12,   12,   13,   13,   13,
   13,   13,   13,   13,    2,    2,    2,    8,    8,    8,
    7,    7,    7,    9,    9,   14,   14,   14,   29,   30,
   30,   15,   20,   20,   20,   20,   20,   20,   20,   22,
   22,   22,   23,   23,   23,   23,   24,   24,   24,   25,
   25,   25,   25,   25,    4,   10,   10,   26,   26,   26,
    1,    1,    1,    1,    1,
};
static const YYINT yylen[] = {                            2,
    2,    0,    2,    0,    1,    1,    1,    2,    1,    1,
    0,    1,    1,    1,    2,    1,    1,    0,    1,    0,
    5,    4,    1,    1,    3,    1,    1,    1,    4,    4,
    4,    4,    4,    4,    6,    8,    9,    2,    3,    3,
    3,    3,    3,    3,    2,    4,    0,    5,    3,    5,
    3,    5,    5,    1,    1,    7,    8,    8,    4,    9,
    9,    7,    3,    3,    3,    3,    3,    3,    1,    3,
    3,    1,    3,    3,    3,    1,    2,    2,    1,    3,
    1,    1,    1,    1,    1,    5,    5,    1,    1,    1,
    1,    1,    1,    1,    1,
};
static const YYINT yydefred[] = {                         2,
    0,    0,    0,    0,   82,   83,   93,   91,   94,   92,
   95,    0,    0,    0,    0,    1,    5,    6,    9,   10,
   54,   55,   84,    0,    7,    0,    0,    0,   79,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,   19,    0,    0,    0,    0,    0,    0,    8,    0,
    0,    0,    0,    0,   77,   78,    0,    0,   80,   49,
    0,    0,   82,   83,   90,   27,    0,   24,    0,   28,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,   22,   29,   30,   31,   32,   33,
   34,    4,    4,   50,   48,   45,    0,    0,   88,   89,
   85,   25,    0,    0,    0,   35,    4,    0,    0,    0,
    0,    3,   12,   13,   17,   16,    0,   14,   62,   46,
    0,    0,    0,   57,   58,    0,    0,   15,   36,    0,
    0,    0,    0,    0,    4,   51,    0,    0,   38,    0,
    0,    0,    0,    0,    0,   37,    0,    0,    0,    0,
    0,    0,    0,   39,   40,   41,   42,   44,   43,   87,
   86,    0,   59,   53,   52,   21,    0,    4,    0,    0,
   60,   61,
};
static const YYINT yydgoto[] = {                          1,
  120,   93,   14,   15,  122,   16,  123,   17,  124,  125,
   19,   20,  141,   21,   22,  126,   23,   67,   68,  127,
  128,   26,   27,   28,   29,   70,  113,   49,  134,  135,
};
static const YYINT yysindex[] = {                         0,
  -55, -277, -270, -262,    0,    0,    0,    0,    0,    0,
    0,    0, -283, -263,  -63,    0,    0,    0,    0,    0,
    0,    0,    0,   15,    0, -241,  -88, -185,    0, -262,
 -262,    0, -203, -248, -186, -262, -262, -262, -262, -262,
 -262,    0, -262, -262, -262, -262, -262, -262,    0, -262,
 -262, -262, -262, -262,    0,    0, -129, -122,    0,    0,
 -136, -225,    0,    0,    0,    0, -259,    0,  323,    0,
  118, -233, -214, -206, -198, -236, -241, -241, -241, -241,
 -241, -241,  -88,  -88, -185, -185, -185, -205, -189,  169,
 -156, -196, -254, -182,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0, -225, -251,    0,    0,
    0,    0,  -64,  834, -195,    0,    0, -174, -201, -184,
 -154,    0,    0,    0,    0,    0,   15,    0,    0,    0,
 -120, -255, -249,    0,    0, -247, -186,    0,    0, -250,
 -159, -134, -133, -135,    0,    0, -136, -231,    0, -101,
  -99,  -96,  -87,  -75,  220,    0,  -72,  -71, -262,  861,
  271,  -70,  -69,    0,    0,    0,    0,    0,    0,    0,
    0,  458,    0,    0,    0,    0, -118,    0,  888, -201,
    0,    0,
};
static const YYINT yyrindex[] = {                         0,
  195,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,   53,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,  807,    0,  465,  312,  104,    0,    0,
    0,    1,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0, -216,    0,    0,    0,    0,    0,    0, -215,    0,
    0,    0,    0,    0,    0,    0,  516,  567,  618,  669,
  720,  771,  363,  414,  155,  206,  257,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,  798,    0,
    0,    0,    0,    0,    0,    0,  -91,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,  934,  947,    0,    0,    0,    0,    0,    0,    0,
    0,    0, -173,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,
};
static const YYINT yygindex[] = {                         0,
    3,    0, -106,  -30,    0,    0,    0,    0,  196,    0,
    0,    0,    0,    0,    0,    0,    0,   59,  105,   -1,
  199,  600,   58,  -37,  192,  -59,  -97,   75,   25,   27,
};
#define YYTABLESIZE 1221
static const YYINT yytable[] = {                         24,
   81,   91,   33,   13,   66,  114,  121,  121,  144,  116,
  149,   30,   60,  146,   85,   86,   87,   94,   31,  131,
   50,   51,  107,   34,  121,   35,    4,   97,   57,   58,
   95,   61,  147,   69,   71,  108,    5,    6,    4,  117,
   62,  145,  150,  151,   32,   94,   98,  160,  152,  153,
  142,  143,   81,  121,   99,  154,   32,  133,  163,   90,
   47,   26,  100,   66,   92,   43,   44,   45,   46,   47,
   48,  101,  121,   47,   26,    7,    8,    9,   10,   11,
  179,   55,   56,   22,   22,  102,   59,  162,   22,   22,
   22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
   22,  103,    4,   76,  105,   22,   66,   83,   84,  115,
  106,  130,   63,   64,  132,   22,  109,  110,   22,   65,
   12,   22,  136,   65,  111,   22,   22,   22,   22,   22,
   22,   22,  156,   22,  137,   69,  118,    2,  155,   43,
   44,   45,   46,   47,   48,  161,   43,   44,   45,   46,
   47,   48,    4,  159,   73,  157,  158,  172,    3,  164,
   88,  165,   63,   64,  166,   20,   20,   89,    4,   65,
   32,  139,  178,  167,  140,   52,   53,   54,    5,    6,
    7,    8,    9,   10,   11,  168,   12,   20,  170,  171,
  175,  176,  118,    2,   11,  148,   18,   20,  112,   25,
   20,  138,    2,   20,  181,   74,  182,   20,   20,   20,
   20,   20,   20,   20,    3,   20,   36,   37,   38,   39,
   40,   41,    0,    3,    4,    0,    0,  119,   72,   73,
   74,   75,   76,    4,    5,    6,    7,    8,    9,   10,
   11,    0,   12,    5,    6,    7,    8,    9,   10,   11,
    0,   12,    0,    0,    0,    0,   75,   81,   81,    0,
    0,   81,   81,   81,   81,   81,   81,   81,   81,   81,
   81,   81,   81,   81,   81,   42,    0,   81,    0,   81,
    0,    0,    0,   43,   44,   45,   46,   47,   48,   23,
   81,    0,   81,    0,    0,   81,    0,    0,    0,   81,
   81,   81,   81,   81,   81,   81,    0,   81,   81,   81,
   81,   72,    0,   81,   81,   81,   81,   81,   81,   81,
   81,   81,   81,   81,   81,   81,   81,    0,    0,   81,
    0,   81,   85,   85,   85,   85,   85,   85,    0,    0,
    0,   23,   81,    0,   81,    0,    0,   81,    0,    0,
    0,   81,   81,   81,   81,   81,   81,   81,    0,   81,
   76,   76,   70,    0,   76,   76,   76,   76,   76,   76,
    0,    0,   76,   76,   76,   76,   76,   76,   96,    0,
   76,    0,   76,    0,    0,    0,   43,   44,   45,   46,
   47,   48,   76,   76,    0,   76,    0,    0,   76,    0,
    0,    0,   76,   76,   76,   76,   76,   76,   76,    0,
   76,   73,   73,   71,    0,   73,   73,   73,   73,   73,
   73,    0,    0,   73,   73,   73,   73,   73,   73,  104,
    0,   73,    0,   73,    0,    0,    0,   43,   44,   45,
   46,   47,   48,   73,   73,    0,   73,    0,    0,   73,
    0,    0,    0,   73,   73,   73,   73,   73,   73,   73,
    0,   73,   74,   74,   69,    0,   74,   74,   74,   74,
   74,   74,    0,    0,   74,   74,   74,   74,   74,   74,
  169,    0,   74,    0,   74,    0,    0,    0,   43,   44,
   45,   46,   47,   48,   74,   74,    0,   74,    0,    0,
   74,    0,    0,    0,   74,   74,   74,   74,   74,   74,
   74,    0,   74,   75,   75,   67,    0,   75,   75,   75,
   75,   75,   75,    0,    0,   75,   75,   75,   75,   75,
   75,  174,    0,   75,    0,   75,    0,    0,    0,   43,
   44,   45,   46,   47,   48,   75,   75,    0,   75,    0,
    0,   75,    0,    0,    0,   75,   75,   75,   75,   75,
   75,   75,    0,   75,    0,    0,   68,    0,   72,   72,
    0,    0,   72,   72,   72,    0,    0,    0,    0,    0,
   72,   72,   72,   72,   72,   72,    0,    0,   72,    0,
   72,   43,   44,   45,   46,   47,   48,    0,    0,    0,
   72,   72,    0,   72,    0,    0,   72,    0,    0,    0,
   72,   72,   72,   72,   72,   72,   72,   64,   72,   70,
   70,    0,    0,   70,   70,   70,    0,    0,    0,    0,
    0,   70,   70,   70,   70,   70,   70,    0,    0,   70,
    0,   70,   77,   78,   79,   80,   81,   82,    0,    0,
    0,   70,   70,    0,   70,    0,    0,   70,    0,    0,
    0,   70,   70,   70,   70,   70,   70,   70,   65,   70,
   71,   71,    0,    0,   71,   71,   71,    0,    0,    0,
    0,    0,   71,   71,   71,   71,   71,   71,    0,    0,
   71,    0,   71,    0,    0,    0,    0,    0,    0,    0,
    0,    0,   71,   71,    0,   71,    0,    0,   71,    0,
    0,    0,   71,   71,   71,   71,   71,   71,   71,   63,
   71,   69,   69,    0,    0,   69,   43,   44,   45,   46,
   47,   48,    0,   69,   69,   69,   69,   69,   69,    0,
    0,   69,    0,   69,    0,    0,    0,  177,    0,    0,
    0,    0,    0,   69,   69,    0,   69,    0,    0,   69,
    0,    0,    0,   69,   69,   69,   69,   69,   69,   69,
   66,   69,   67,   67,    0,    0,   67,    0,    0,    0,
    0,    0,    0,    0,   67,   67,   67,   67,   67,   67,
    0,    0,   67,    0,   67,    0,    0,   56,    0,    0,
    0,    0,    0,    0,   67,   67,   20,   67,    0,    0,
   67,    0,    0,    0,   67,   67,   67,   67,   67,   67,
   67,    0,   67,   68,   68,    0,    0,   68,    0,    0,
    0,    0,    0,    0,    0,   68,   68,   68,   68,   68,
   68,    0,    0,   68,    0,   68,    0,    0,    0,    0,
    0,    0,    0,    0,    0,   68,   68,    0,   68,    0,
    0,   68,    0,    0,    0,   68,   68,   68,   68,   68,
   68,   68,    0,   68,   64,   64,    0,    0,   64,    0,
    0,    0,    0,    0,    0,    0,   64,   64,   64,   64,
   64,   64,    0,    0,   64,    0,   64,    0,    0,    0,
    0,    0,    0,    0,    0,    0,   64,   64,    0,   64,
    0,    0,   64,    0,    0,    0,   64,   64,   64,   64,
   64,   64,   64,    0,   64,   65,   65,    0,    0,   65,
    0,    0,    0,    0,    0,    0,    0,   65,   65,   65,
   65,   65,   65,    0,    0,   65,    0,   65,    0,    0,
    0,    0,    0,    0,    0,    0,    0,   65,   65,    0,
   65,    0,    0,   65,    0,    0,    0,   65,   65,   65,
   65,   65,   65,   65,    0,   65,   63,   63,    0,    0,
   63,    0,    0,    0,    0,    0,    0,    0,   63,   63,
   63,   63,   63,   63,    0,    0,   63,    0,   63,    0,
    0,    0,    0,    0,    0,    0,    0,    0,   63,   63,
    0,   63,    0,    0,   63,    0,    0,    0,   63,   63,
   63,   63,   63,   63,   63,    0,   63,   66,   66,    0,
    0,   66,    0,    0,    0,    0,    0,    0,    0,   66,
   66,   66,   66,   66,   66,    0,    0,   66,    0,   66,
    0,    0,    0,    0,   56,   56,    0,    0,    0,   66,
   66,    0,   66,    0,   20,   66,    0,    0,    0,   66,
   66,   66,   66,   66,   66,   66,   56,   66,    0,    0,
    0,    0,    0,    0,    0,   20,   56,    0,    0,   56,
  118,    2,   56,    0,    0,   20,   56,   56,   56,   56,
   56,   56,   56,    0,   56,   20,   20,   20,   20,   20,
   20,   20,    3,   20,    0,    0,    0,  118,    2,    0,
    0,    0,    4,    0,    0,  129,    0,    0,    0,    0,
    0,    0,    5,    6,    7,    8,    9,   10,   11,    3,
   12,    0,    0,    0,  118,    2,    0,    0,    0,    4,
    0,    0,  173,    0,    0,    0,    0,    0,    0,    5,
    6,    7,    8,    9,   10,   11,    3,   12,    0,    0,
    0,    0,    0,    0,    0,    0,    4,    0,    0,  180,
    0,    0,    0,    0,    0,    0,    5,    6,    7,    8,
    9,   10,   11,    0,   12,   82,   82,   82,   82,   82,
   82,   82,   82,   82,   82,   82,   82,   82,   83,   83,
   83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
   83,
};
static const YYINT yycheck[] = {                          1,
    0,   61,    4,    1,   35,  103,  113,  114,  258,  261,
  261,  289,  261,  261,   52,   53,   54,  277,  289,  117,
  262,  263,  277,  307,  131,  289,  289,  261,   30,   31,
  290,  280,  280,   35,   36,  290,  299,  300,  289,  291,
  289,  291,  293,  294,  307,  277,  261,  145,  299,  300,
  306,  307,    0,  160,  261,  306,  307,  259,  290,   61,
  277,  277,  261,   94,   62,  269,  270,  271,  272,  273,
  274,  308,  179,  290,  290,  301,  302,  303,  304,  305,
  178,  267,  268,  257,  258,  291,  290,  147,  262,  263,
  264,  265,  266,  267,  268,  269,  270,  271,  272,  273,
  274,  291,  289,    0,  261,  279,  137,   50,   51,  107,
  307,  307,  299,  300,  289,  289,  299,  300,  292,  306,
  307,  295,  307,  306,  307,  299,  300,  301,  302,  303,
  304,  305,  292,  307,  289,  137,  257,  258,  140,  269,
  270,  271,  272,  273,  274,  147,  269,  270,  271,  272,
  273,  274,  289,  289,    0,  290,  290,  159,  279,  261,
  290,  261,  299,  300,  261,  257,  258,  290,  289,  306,
  307,  292,  291,  261,  295,  264,  265,  266,  299,  300,
  301,  302,  303,  304,  305,  261,  307,  279,  261,  261,
  261,  261,  257,  258,    0,  137,    1,  289,   94,    1,
  292,  127,  258,  295,  180,    0,  180,  299,  300,  301,
  302,  303,  304,  305,  279,  307,  280,  281,  282,  283,
  284,  285,   -1,  279,  289,   -1,   -1,  292,   37,   38,
   39,   40,   41,  289,  299,  300,  301,  302,  303,  304,
  305,   -1,  307,  299,  300,  301,  302,  303,  304,  305,
   -1,  307,   -1,   -1,   -1,   -1,    0,  257,  258,   -1,
   -1,  261,  262,  263,  264,  265,  266,  267,  268,  269,
  270,  271,  272,  273,  274,  261,   -1,  277,   -1,  279,
   -1,   -1,   -1,  269,  270,  271,  272,  273,  274,  289,
  290,   -1,  292,   -1,   -1,  295,   -1,   -1,   -1,  299,
  300,  301,  302,  303,  304,  305,   -1,  307,  308,  257,
  258,    0,   -1,  261,  262,  263,  264,  265,  266,  267,
  268,  269,  270,  271,  272,  273,  274,   -1,   -1,  277,
   -1,  279,  280,  281,  282,  283,  284,  285,   -1,   -1,
   -1,  289,  290,   -1,  292,   -1,   -1,  295,   -1,   -1,
   -1,  299,  300,  301,  302,  303,  304,  305,   -1,  307,
  257,  258,    0,   -1,  261,  262,  263,  264,  265,  266,
   -1,   -1,  269,  270,  271,  272,  273,  274,  261,   -1,
  277,   -1,  279,   -1,   -1,   -1,  269,  270,  271,  272,
  273,  274,  289,  290,   -1,  292,   -1,   -1,  295,   -1,
   -1,   -1,  299,  300,  301,  302,  303,  304,  305,   -1,
  307,  257,  258,    0,   -1,  261,  262,  263,  264,  265,
  266,   -1,   -1,  269,  270,  271,  272,  273,  274,  261,
   -1,  277,   -1,  279,   -1,   -1,   -1,  269,  270,  271,
  272,  273,  274,  289,  290,   -1,  292,   -1,   -1,  295,
   -1,   -1,   -1,  299,  300,  301,  302,  303,  304,  305,
   -1,  307,  257,  258,    0,   -1,  261,  262,  263,  264,
  265,  266,   -1,   -1,  269,  270,  271,  272,  273,  274,
  261,   -1,  277,   -1,  279,   -1,   -1,   -1,  269,  270,
  271,  272,  273,  274,  289,  290,   -1,  292,   -1,   -1,
  295,   -1,   -1,   -1,  299,  300,  301,  302,  303,  304,
  305,   -1,  307,  257,  258,    0,   -1,  261,  262,  263,
  264,  265,  266,   -1,   -1,  269,  270,  271,  272,  273,
  274,  261,   -1,  277,   -1,  279,   -1,   -1,   -1,  269,
  270,  271,  272,  273,  274,  289,  290,   -1,  292,   -1,
   -1,  295,   -1,   -1,   -1,  299,  300,  301,  302,  303,
  304,  305,   -1,  307,   -1,   -1,    0,   -1,  257,  258,
   -1,   -1,  261,  262,  263,   -1,   -1,   -1,   -1,   -1,
  269,  270,  271,  272,  273,  274,   -1,   -1,  277,   -1,
  279,  269,  270,  271,  272,  273,  274,   -1,   -1,   -1,
  289,  290,   -1,  292,   -1,   -1,  295,   -1,   -1,   -1,
  299,  300,  301,  302,  303,  304,  305,    0,  307,  257,
  258,   -1,   -1,  261,  262,  263,   -1,   -1,   -1,   -1,
   -1,  269,  270,  271,  272,  273,  274,   -1,   -1,  277,
   -1,  279,   43,   44,   45,   46,   47,   48,   -1,   -1,
   -1,  289,  290,   -1,  292,   -1,   -1,  295,   -1,   -1,
   -1,  299,  300,  301,  302,  303,  304,  305,    0,  307,
  257,  258,   -1,   -1,  261,  262,  263,   -1,   -1,   -1,
   -1,   -1,  269,  270,  271,  272,  273,  274,   -1,   -1,
  277,   -1,  279,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
   -1,   -1,  289,  290,   -1,  292,   -1,   -1,  295,   -1,
   -1,   -1,  299,  300,  301,  302,  303,  304,  305,    0,
  307,  257,  258,   -1,   -1,  261,  269,  270,  271,  272,
  273,  274,   -1,  269,  270,  271,  272,  273,  274,   -1,
   -1,  277,   -1,  279,   -1,   -1,   -1,  290,   -1,   -1,
   -1,   -1,   -1,  289,  290,   -1,  292,   -1,   -1,  295,
   -1,   -1,   -1,  299,  300,  301,  302,  303,  304,  305,
    0,  307,  257,  258,   -1,   -1,  261,   -1,   -1,   -1,
   -1,   -1,   -1,   -1,  269,  270,  271,  272,  273,  274,
   -1,   -1,  277,   -1,  279,   -1,   -1,    0,   -1,   -1,
   -1,   -1,   -1,   -1,  289,  290,    0,  292,   -1,   -1,
  295,   -1,   -1,   -1,  299,  300,  301,  302,  303,  304,
  305,   -1,  307,  257,  258,   -1,   -1,  261,   -1,   -1,
   -1,   -1,   -1,   -1,   -1,  269,  270,  271,  272,  273,
  274,   -1,   -1,  277,   -1,  279,   -1,   -1,   -1,   -1,
   -1,   -1,   -1,   -1,   -1,  289,  290,   -1,  292,   -1,
   -1,  295,   -1,   -1,   -1,  299,  300,  301,  302,  303,
  304,  305,   -1,  307,  257,  258,   -1,   -1,  261,   -1,
   -1,   -1,   -1,   -1,   -1,   -1,  269,  270,  271,  272,
  273,  274,   -1,   -1,  277,   -1,  279,   -1,   -1,   -1,
   -1,   -1,   -1,   -1,   -1,   -1,  289,  290,   -1,  292,
   -1,   -1,  295,   -1,   -1,   -1,  299,  300,  301,  302,
  303,  304,  305,   -1,  307,  257,  258,   -1,   -1,  261,
   -1,   -1,   -1,   -1,   -1,   -1,   -1,  269,  270,  271,
  272,  273,  274,   -1,   -1,  277,   -1,  279,   -1,   -1,
   -1,   -1,   -1,   -1,   -1,   -1,   -1,  289,  290,   -1,
  292,   -1,   -1,  295,   -1,   -1,   -1,  299,  300,  301,
  302,  303,  304,  305,   -1,  307,  257,  258,   -1,   -1,
  261,   -1,   -1,   -1,   -1,   -1,   -1,   -1,  269,  270,
  271,  272,  273,  274,   -1,   -1,  277,   -1,  279,   -1,
   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,  289,  290,
   -1,  292,   -1,   -1,  295,   -1,   -1,   -1,  299,  300,
  301,  302,  303,  304,  305,   -1,  307,  257,  258,   -1,
   -1,  261,   -1,   -1,   -1,   -1,   -1,   -1,   -1,  269,
  270,  271,  272,  273,  274,   -1,   -1,  277,   -1,  279,
   -1,   -1,   -1,   -1,  257,  258,   -1,   -1,   -1,  289,
  290,   -1,  292,   -1,  258,  295,   -1,   -1,   -1,  299,
  300,  301,  302,  303,  304,  305,  279,  307,   -1,   -1,
   -1,   -1,   -1,   -1,   -1,  279,  289,   -1,   -1,  292,
  257,  258,  295,   -1,   -1,  289,  299,  300,  301,  302,
  303,  304,  305,   -1,  307,  299,  300,  301,  302,  303,
  304,  305,  279,  307,   -1,   -1,   -1,  257,  258,   -1,
   -1,   -1,  289,   -1,   -1,  292,   -1,   -1,   -1,   -1,
   -1,   -1,  299,  300,  301,  302,  303,  304,  305,  279,
  307,   -1,   -1,   -1,  257,  258,   -1,   -1,   -1,  289,
   -1,   -1,  292,   -1,   -1,   -1,   -1,   -1,   -1,  299,
  300,  301,  302,  303,  304,  305,  279,  307,   -1,   -1,
   -1,   -1,   -1,   -1,   -1,   -1,  289,   -1,   -1,  292,
   -1,   -1,   -1,   -1,   -1,   -1,  299,  300,  301,  302,
  303,  304,  305,   -1,  307,  262,  263,  264,  265,  266,
  267,  268,  269,  270,  271,  272,  273,  274,  262,  263,
  264,  265,  266,  267,  268,  269,  270,  271,  272,  273,
  274,
};
#define YYFINAL 1
#ifndef YYDEBUG
#define YYDEBUG 0
#endif
#define YYMAXTOKEN 308
#define YYUNDFTOKEN 341
#define YYTRANSLATE(a) ((a) > YYMAXTOKEN ? YYUNDFTOKEN : (a))
#if YYDEBUG
static const char *const yyname[] = {

"end-of-file",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"PRINT","IF","ELSE","FOR",
"SEMICOLON","ADD","SUB","MUL","DIV","MOD","INC","DEC","MT","LT","MTE","LTE",
"EQ","NE","LSB","RSB","COMMA","QUOTA","WHILE","ASGN","ADDASGN","SUBASGN",
"MULASGN","DIVASGN","MODASGN","AND","OR","NOT","LB","RB","LCB","RCB","TRUE",
"FALSE","RET","CONT","BREAK","COMMENT","I_CONST","F_CONST","BOOL","INT",
"STRING","FLOAT","VOID","STR_CONST","ID","SEMICOLONE",0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"illegal-symbol",
};
static const char *const yyrule[] = {
"$accept : program",
"program : program stat",
"program :",
"fprogram : fprogram fstat",
"fprogram :",
"stat : declaration",
"stat : compound_stat",
"stat : expr_asgn",
"stat : expression_stat4 semicolon",
"stat : function_decl",
"stat : function_def",
"stat :",
"fstat : fdeclaration",
"fstat : compound_stat",
"fstat : expr_asgn",
"fstat : expression_stat4 semicolon",
"fstat : direct_function_call",
"fstat : print_func",
"fstat :",
"semicolon : SEMICOLON",
"semicolon :",
"direct_function_call : func_id LB parameter RB SEMICOLON",
"function_call : func_id LB parameter RB",
"func_id : ID",
"parameter : pass",
"parameter : parameter COMMA pass",
"parameter : expression_stat4",
"pass : id",
"pass : initializer",
"expr_asgn : id ASGN expression_stat4 SEMICOLON",
"expr_asgn : id ADDASGN factor SEMICOLON",
"expr_asgn : id SUBASGN factor SEMICOLON",
"expr_asgn : id MULASGN factor SEMICOLON",
"expr_asgn : id DIVASGN factor SEMICOLON",
"expr_asgn : id MODASGN factor SEMICOLONE",
"function_decl : type ID LB argument RB SEMICOLON",
"function_def : type ID LB argument RB LCB fprogram RCB",
"function_def : type ID LB argument RB LCB fprogram return RCB",
"return : RET SEMICOLON",
"return : RET TRUE SEMICOLON",
"return : RET FALSE SEMICOLON",
"return : RET I_CONST SEMICOLON",
"return : RET F_CONST SEMICOLON",
"return : RET expression_stat4 SEMICOLON",
"return : RET STR_CONST SEMICOLON",
"argument : type ID",
"argument : argument COMMA type ID",
"argument :",
"declaration : type ID ASGN initializer SEMICOLON",
"declaration : type ID SEMICOLON",
"declaration : type ID ASGN expression_stat4 SEMICOLON",
"fdeclaration : type ID SEMICOLON",
"fdeclaration : type ID ASGN initializer SEMICOLON",
"fdeclaration : type ID ASGN expression_stat4 SEMICOLON",
"compound_stat : if_stat",
"compound_stat : while_stat",
"if_stat : IF LB expression_stat4 RB LCB fprogram RCB",
"if_stat : IF LB expression_stat4 RB LCB fprogram RCB else_stat",
"if_stat : IF LB expression_stat4 RB LCB fprogram RCB elseif_stat",
"else_stat : ELSE LCB fprogram RCB",
"elseif_stat : ELSE IF LB expression_stat4 RB LCB fprogram RCB else_stat",
"elseif_stat : ELSE IF LB expression_stat4 RB LCB fprogram RCB elseif_stat",
"while_stat : WHILE LB expression_stat4 RB LCB fprogram RCB",
"expression_stat4 : expression_stat4 EQ expression_stat3",
"expression_stat4 : expression_stat4 MTE expression_stat3",
"expression_stat4 : expression_stat4 LTE expression_stat3",
"expression_stat4 : expression_stat4 NE expression_stat3",
"expression_stat4 : expression_stat4 MT expression_stat3",
"expression_stat4 : expression_stat4 LT expression_stat3",
"expression_stat4 : expression_stat3",
"expression_stat3 : expression_stat3 ADD expression_stat2",
"expression_stat3 : expression_stat3 SUB expression_stat2",
"expression_stat3 : expression_stat2",
"expression_stat2 : expression_stat2 MUL expression_stat1",
"expression_stat2 : expression_stat2 DIV expression_stat1",
"expression_stat2 : expression_stat2 MOD expression_stat1",
"expression_stat2 : expression_stat1",
"expression_stat1 : expression_stat1 INC",
"expression_stat1 : expression_stat1 DEC",
"expression_stat1 : factor",
"factor : LB expression_stat4 RB",
"factor : ID",
"factor : I_CONST",
"factor : F_CONST",
"factor : function_call",
"id : ID",
"print_func : PRINT LB ID RB SEMICOLON",
"print_func : PRINT LB STR_CONST RB SEMICOLON",
"initializer : I_CONST",
"initializer : F_CONST",
"initializer : STR_CONST",
"type : INT",
"type : FLOAT",
"type : BOOL",
"type : STRING",
"type : VOID",

};
#endif

int      yydebug;
int      yynerrs;

int      yyerrflag;
int      yychar;
YYSTYPE  yyval;
YYSTYPE  yylval;

/* define the initial stack-sizes */
#ifdef YYSTACKSIZE
#undef YYMAXDEPTH
#define YYMAXDEPTH  YYSTACKSIZE
#else
#ifdef YYMAXDEPTH
#define YYSTACKSIZE YYMAXDEPTH
#else
#define YYSTACKSIZE 10000
#define YYMAXDEPTH  10000
#endif
#endif

#define YYINITSTACKSIZE 200

typedef struct {
    unsigned stacksize;
    YYINT    *s_base;
    YYINT    *s_mark;
    YYINT    *s_last;
    YYSTYPE  *l_base;
    YYSTYPE  *l_mark;
} YYSTACKDATA;
/* variables for the parser stack */
static YYSTACKDATA yystack;
#line 552 "compiler_hw2.y"

/* C code section */
int main(int argc, char** argv)
{
    error = 0;
    yerror = 0;
    dump = 0;
    yylineno = 0;
    now_scope = 0;
    symbolno = 0;
    globalno = 0; 
    yyparse();
    if(yerror==0) { 
        dump_symbol(global_table,0,globalno);
        printf("\nTotal lines: %d \n",yylineno);
    }
    return 0;
}

void serror(char *s)
{
    printf("\n|-----------------------------------------------|\n");
    printf("| Error found in line %d: %s\n", yylineno, buf);
    printf("| %s", s);
    printf("\n|-----------------------------------------------|\n\n");
}

void yyerror(char *s)
{
    yerror = 1;
    yylineno++;
    printf("%d: %s\n",yylineno,buf);
    if(error==1)
        serror(errorm);
    printf("\n|-----------------------------------------------|\n");
    printf("| Error found in line %d: %s\n", yylineno, buf);
    printf("| %s", s);
    printf("\n|-----------------------------------------------|\n\n");
}

int lookup_symbol(symbol *t,char *name,int n,int scope,int d){
    int i;
    if(d == 0){  //undeclare
        for(i=0; i<n; i++){	
	        if(strcmp(t[i].name,name)==0)
	            return 1;
        }   
    }
    else{    //redeclar
        for(i=0; i<n; i++){	
	        if(strcmp(t[i].name,name)==0)
                if(t[i].scope==scope)
	                return 1;
        }
    }
    return 0;
}

int check_funcdef(symbol *t,char *name,int n){
    int i;
    for(i=0; i<n; i++){	
	    if(strcmp(t[i].name,name)==0)
            if(t[i].func_def==1)
	            return 1;
    }
    return 0;
}

symbol create_symbol(char *name,char *kind,char *type,int scope,char *attribute){
    symbol s;
    strcpy(s.name,name);
    strcpy(s.kind,kind);
    strcpy(s.type,type);
    s.scope = scope;
    strcpy(s.attribute,attribute);
    return s;
}
void insert_symbol(symbol* t,symbol s,int i){
    strcpy(t[i].name,s.name);
    strcpy(t[i].kind,s.kind);
    strcpy(t[i].type,s.type);
    t[i].scope = s.scope;
    strcpy(t[i].attribute,s.attribute);
}

void dump_symbol(symbol* t,int scope,int n) {
    int yes = 0; 
    int i,j=0;
    for(i=0; i<n; i++){
        if(t[i].scope==scope)
            yes = 1;
    }
    if(yes == 1){
        printf("\n%-10s%-10s%-12s%-10s%-10s%-10s\n\n",
           "Index", "Name", "Kind", "Type", "Scope", "Attribute");
        for(i=0; i<n; i++){
            if(t[i].scope == scope){
                if(strcmp(t[i].attribute,"")==0)
    	            printf("%-10d%-10s%-12s%-10s%-10d\n",j,t[i].name,t[i].kind,t[i].type,t[i].scope);
                else
    	            printf("%-10d%-10s%-12s%-10s%-10d%s\n",j,t[i].name,t[i].kind,t[i].type,t[i].scope,t[i].attribute);
                j++;
                memset(&t[i],0,sizeof(t[i]));
            }
        }
        printf("\n");
    }
}
#line 769 "y.tab.c"

#if YYDEBUG
#include <stdio.h>		/* needed for printf */
#endif

#include <stdlib.h>	/* needed for malloc, etc */
#include <string.h>	/* needed for memset */

/* allocate initial stack or double stack size, up to YYMAXDEPTH */
static int yygrowstack(YYSTACKDATA *data)
{
    int i;
    unsigned newsize;
    YYINT *newss;
    YYSTYPE *newvs;

    if ((newsize = data->stacksize) == 0)
        newsize = YYINITSTACKSIZE;
    else if (newsize >= YYMAXDEPTH)
        return YYENOMEM;
    else if ((newsize *= 2) > YYMAXDEPTH)
        newsize = YYMAXDEPTH;

    i = (int) (data->s_mark - data->s_base);
    newss = (YYINT *)realloc(data->s_base, newsize * sizeof(*newss));
    if (newss == 0)
        return YYENOMEM;

    data->s_base = newss;
    data->s_mark = newss + i;

    newvs = (YYSTYPE *)realloc(data->l_base, newsize * sizeof(*newvs));
    if (newvs == 0)
        return YYENOMEM;

    data->l_base = newvs;
    data->l_mark = newvs + i;

    data->stacksize = newsize;
    data->s_last = data->s_base + newsize - 1;
    return 0;
}

#if YYPURE || defined(YY_NO_LEAKS)
static void yyfreestack(YYSTACKDATA *data)
{
    free(data->s_base);
    free(data->l_base);
    memset(data, 0, sizeof(*data));
}
#else
#define yyfreestack(data) /* nothing */
#endif

#define YYABORT  goto yyabort
#define YYREJECT goto yyabort
#define YYACCEPT goto yyaccept
#define YYERROR  goto yyerrlab

int
YYPARSE_DECL()
{
    int yym, yyn, yystate;
#if YYDEBUG
    const char *yys;

    if ((yys = getenv("YYDEBUG")) != 0)
    {
        yyn = *yys;
        if (yyn >= '0' && yyn <= '9')
            yydebug = yyn - '0';
    }
#endif

    yynerrs = 0;
    yyerrflag = 0;
    yychar = YYEMPTY;
    yystate = 0;

#if YYPURE
    memset(&yystack, 0, sizeof(yystack));
#endif

    if (yystack.s_base == NULL && yygrowstack(&yystack) == YYENOMEM) goto yyoverflow;
    yystack.s_mark = yystack.s_base;
    yystack.l_mark = yystack.l_base;
    yystate = 0;
    *yystack.s_mark = 0;

yyloop:
    if ((yyn = yydefred[yystate]) != 0) goto yyreduce;
    if (yychar < 0)
    {
        if ((yychar = YYLEX) < 0) yychar = YYEOF;
#if YYDEBUG
        if (yydebug)
        {
            yys = yyname[YYTRANSLATE(yychar)];
            printf("%sdebug: state %d, reading %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
    }
    if ((yyn = yysindex[yystate]) && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: state %d, shifting to state %d\n",
                    YYPREFIX, yystate, yytable[yyn]);
#endif
        if (yystack.s_mark >= yystack.s_last && yygrowstack(&yystack) == YYENOMEM)
        {
            goto yyoverflow;
        }
        yystate = yytable[yyn];
        *++yystack.s_mark = yytable[yyn];
        *++yystack.l_mark = yylval;
        yychar = YYEMPTY;
        if (yyerrflag > 0)  --yyerrflag;
        goto yyloop;
    }
    if ((yyn = yyrindex[yystate]) && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
        yyn = yytable[yyn];
        goto yyreduce;
    }
    if (yyerrflag) goto yyinrecovery;

    YYERROR_CALL("syntax error");

    goto yyerrlab;

yyerrlab:
    ++yynerrs;

yyinrecovery:
    if (yyerrflag < 3)
    {
        yyerrflag = 3;
        for (;;)
        {
            if ((yyn = yysindex[*yystack.s_mark]) && (yyn += YYERRCODE) >= 0 &&
                    yyn <= YYTABLESIZE && yycheck[yyn] == YYERRCODE)
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: state %d, error recovery shifting\
 to state %d\n", YYPREFIX, *yystack.s_mark, yytable[yyn]);
#endif
                if (yystack.s_mark >= yystack.s_last && yygrowstack(&yystack) == YYENOMEM)
                {
                    goto yyoverflow;
                }
                yystate = yytable[yyn];
                *++yystack.s_mark = yytable[yyn];
                *++yystack.l_mark = yylval;
                goto yyloop;
            }
            else
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: error recovery discarding state %d\n",
                            YYPREFIX, *yystack.s_mark);
#endif
                if (yystack.s_mark <= yystack.s_base) goto yyabort;
                --yystack.s_mark;
                --yystack.l_mark;
            }
        }
    }
    else
    {
        if (yychar == YYEOF) goto yyabort;
#if YYDEBUG
        if (yydebug)
        {
            yys = yyname[YYTRANSLATE(yychar)];
            printf("%sdebug: state %d, error recovery discards token %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
        yychar = YYEMPTY;
        goto yyloop;
    }

yyreduce:
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: state %d, reducing by rule %d (%s)\n",
                YYPREFIX, yystate, yyn, yyrule[yyn]);
#endif
    yym = yylen[yyn];
    if (yym)
        yyval = yystack.l_mark[1-yym];
    else
        memset(&yyval, 0, sizeof yyval);
    switch (yyn)
    {
case 1:
#line 77 "compiler_hw2.y"
	{ 
/*dump_symbol(global_table,0,globalno); */
    }
break;
case 2:
#line 81 "compiler_hw2.y"
	{
       /* dump_symbol(global_table,0,globalno);*/
        globalno = 0;
    }
break;
case 5:
#line 94 "compiler_hw2.y"
	{
    	yyval.f_val = yystack.l_mark[0].f_val;
    }
break;
case 6:
#line 97 "compiler_hw2.y"
	{
    	yyval.f_val = yystack.l_mark[0].f_val;
    }
break;
case 7:
#line 100 "compiler_hw2.y"
	{
    	yyval.f_val = yystack.l_mark[0].f_val;
    }
break;
case 8:
#line 103 "compiler_hw2.y"
	{
    	yyval.f_val = yystack.l_mark[-1].f_val;
    }
break;
case 9:
#line 106 "compiler_hw2.y"
	{
    	yyval.f_val = yystack.l_mark[0].f_val;
    }
break;
case 10:
#line 109 "compiler_hw2.y"
	{
       /* dump = 1;*/
/*        now_scope++;*/
    	yyval.f_val = yystack.l_mark[0].f_val;
    }
break;
case 11:
#line 114 "compiler_hw2.y"
	{ yyval.f_val = 0.1; }
break;
case 12:
#line 119 "compiler_hw2.y"
	{
	    yyval.f_val = yystack.l_mark[0].f_val;
    }
break;
case 13:
#line 122 "compiler_hw2.y"
	{
	    yyval.f_val = yystack.l_mark[0].f_val;
    }
break;
case 14:
#line 125 "compiler_hw2.y"
	{
	    yyval.f_val = yystack.l_mark[0].f_val;
    }
break;
case 15:
#line 128 "compiler_hw2.y"
	{
	    yyval.f_val = yystack.l_mark[-1].f_val;
    }
break;
case 16:
#line 131 "compiler_hw2.y"
	{
    	yyval.f_val = yystack.l_mark[0].f_val;
    }
break;
case 17:
#line 134 "compiler_hw2.y"
	{
    	yyval.f_val = yystack.l_mark[0].f_val;
    }
break;
case 18:
#line 137 "compiler_hw2.y"
	{ yyval.f_val = 0.1; }
break;
case 21:
#line 146 "compiler_hw2.y"
	{
        if(lookup_symbol(global_table,yystack.l_mark[-4].string,globalno,0,0)==0){
            error = 1;
            sprintf(errorm,"Undeclared function %s",yystack.l_mark[-4].string);
        }
    }
break;
case 22:
#line 156 "compiler_hw2.y"
	{
        if(lookup_symbol(global_table,yystack.l_mark[-3].string,globalno,0,0)==0){
            error = 1;
            sprintf(errorm,"Undeclared function %s",yystack.l_mark[-3].string);
        }
    }
break;
case 23:
#line 165 "compiler_hw2.y"
	{
        if(lookup_symbol(global_table,yystack.l_mark[0].string,globalno,0,0)==0){
            error = 1;
            sprintf(errorm,"Undeclared function %s",yystack.l_mark[0].string);
        }
        yyval.string = yystack.l_mark[0].string; 
    }
break;
case 24:
#line 175 "compiler_hw2.y"
	{
        yyval.f_val = 0.1;
    }
break;
case 25:
#line 178 "compiler_hw2.y"
	{
    
        yyval.f_val = 0.1;
    }
break;
case 26:
#line 182 "compiler_hw2.y"
	{
        yyval.f_val = 0.1;
    }
break;
case 27:
#line 188 "compiler_hw2.y"
	{
        yyval.f_val = 0.1;
    }
break;
case 28:
#line 191 "compiler_hw2.y"
	{
        yyval.f_val = 0.1;
    }
break;
case 29:
#line 197 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 30:
#line 200 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 31:
#line 203 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 32:
#line 206 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 33:
#line 209 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 34:
#line 212 "compiler_hw2.y"
	{
  	    yyval.f_val = 0.1;
    }
break;
case 35:
#line 218 "compiler_hw2.y"
	{
        if(lookup_symbol(global_table,yystack.l_mark[-4].string,globalno,0,1)==0){
            symbol s = create_symbol(yystack.l_mark[-4].string,"function",yystack.l_mark[-5].string,0,yystack.l_mark[-2].string);
            s.func_def = 0;
            insert_symbol(global_table,s,globalno);
            globalno++; 
        }
        else {
            error = 1;
            sprintf(errorm,"Redeclared function %s",yystack.l_mark[-4].string);
        }
        memset(symbol_table,0,sizeof symbol_table);
        symbolno = 0;
        yyval.f_val = 0.1;
    }
break;
case 36:
#line 236 "compiler_hw2.y"
	{
        if(lookup_symbol(global_table,yystack.l_mark[-6].string,globalno,0,1)==0){
           symbol s = create_symbol(yystack.l_mark[-6].string,"function",yystack.l_mark[-7].string,0,yystack.l_mark[-4].string);
            s.func_def = 1;
            insert_symbol(global_table,s,globalno);
            globalno++; 
        }
        else {
            if(check_funcdef(global_table,yystack.l_mark[-6].string,globalno)==1){
                error = 1;
                sprintf(errorm,"Redeclared function %s",yystack.l_mark[-6].string);
            }
       }
        yyval.f_val = 0.1;
    }
break;
case 37:
#line 251 "compiler_hw2.y"
	{
        if(lookup_symbol(global_table,yystack.l_mark[-7].string,globalno,0,1)==0){
           symbol s = create_symbol(yystack.l_mark[-7].string,"function",yystack.l_mark[-8].string,0,yystack.l_mark[-5].string);
            s.func_def = 1;
            insert_symbol(global_table,s,globalno);
            globalno++; 
        }
        else {
            if(check_funcdef(global_table,yystack.l_mark[-7].string,globalno)==1){
                error = 1;
                sprintf(errorm,"Redeclared function %s",yystack.l_mark[-7].string);
            }
       }
        yyval.f_val = 0.1;
    }
break;
case 38:
#line 269 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 39:
#line 272 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 40:
#line 275 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 41:
#line 278 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 42:
#line 281 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 43:
#line 284 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 44:
#line 287 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 45:
#line 293 "compiler_hw2.y"
	{
        symbol s = create_symbol(yystack.l_mark[0].string,"parameter",yystack.l_mark[-1].string,1,"");
        insert_symbol(symbol_table,s,symbolno);
        symbolno++;
        yyval.string = yystack.l_mark[-1].string;
    }
break;
case 46:
#line 299 "compiler_hw2.y"
	{
        symbol s = create_symbol(yystack.l_mark[0].string,"parameter",yystack.l_mark[-1].string,1,"");
        insert_symbol(symbol_table,s,symbolno);
        symbolno++;
        yyval.string = strcat(yystack.l_mark[-3].string,", ");
        yyval.string = strcat(yyval.string,yystack.l_mark[-1].string);
    }
break;
case 47:
#line 306 "compiler_hw2.y"
	{
        yyval.string = ""; 
    }
break;
case 48:
#line 312 "compiler_hw2.y"
	{
        if(lookup_symbol(global_table,yystack.l_mark[-3].string,globalno,0,1)==0){
            symbol s = create_symbol(yystack.l_mark[-3].string,"variable",yystack.l_mark[-4].string,0,"");
            insert_symbol(global_table,s,globalno);
            globalno++; 
        }
        else {
            error = 1;
            sprintf(errorm,"Redeclared variable %s",yystack.l_mark[-3].string);
        }
     	yyval.f_val = 0.1;
    }
break;
case 49:
#line 324 "compiler_hw2.y"
	{
        if(lookup_symbol(global_table,yystack.l_mark[-1].string,globalno,0,1)==0){
            symbol s = create_symbol(yystack.l_mark[-1].string,"variable",yystack.l_mark[-2].string,0,"");
            insert_symbol(global_table,s,globalno);
            globalno++; 
        }
        else {
            error = 1;
            sprintf(errorm,"Redeclared variable %s",yystack.l_mark[-1].string);
        }
    	yyval.f_val = 0.1;
    }
break;
case 50:
#line 336 "compiler_hw2.y"
	{
        if(lookup_symbol(global_table,yystack.l_mark[-3].string,globalno,0,1)==0){
            symbol s = create_symbol(yystack.l_mark[-3].string,"variable",yystack.l_mark[-4].string,0,"");
            insert_symbol(global_table,s,globalno);
            globalno++; 
        }
        else {
            error = 1;
            sprintf(errorm,"Redeclared variable %s",yystack.l_mark[-3].string);
        }
      	yyval.f_val = 0.1;
    }
break;
case 51:
#line 351 "compiler_hw2.y"
	{
        if(lookup_symbol(symbol_table,yystack.l_mark[-1].string,symbolno,now_scope,1)==0){
            symbol s = create_symbol(yystack.l_mark[-1].string,"variable",yystack.l_mark[-2].string,now_scope,"");
            insert_symbol(symbol_table,s,symbolno);
            symbolno++; 
        }
        else {
            error = 1;
            sprintf(errorm,"Redeclared variable %s",yystack.l_mark[-1].string);
        }
    	yyval.f_val = 0.1;
    }
break;
case 52:
#line 363 "compiler_hw2.y"
	{
        if(lookup_symbol(symbol_table,yystack.l_mark[-3].string,symbolno,now_scope,1)==0){
            symbol s = create_symbol(yystack.l_mark[-3].string,"variable",yystack.l_mark[-4].string,now_scope,"");
            insert_symbol(symbol_table,s,symbolno);
            symbolno++; 
        }
        else {
            error = 1;
            sprintf(errorm,"Redeclared variable %s",yystack.l_mark[-3].string);
         }
      	yyval.f_val = 0.1;
    }
break;
case 53:
#line 375 "compiler_hw2.y"
	{
        if(lookup_symbol(symbol_table,yystack.l_mark[-3].string,symbolno,now_scope,1)==0){
            symbol s = create_symbol(yystack.l_mark[-3].string,"variable",yystack.l_mark[-4].string,now_scope,"");
            insert_symbol(symbol_table,s,symbolno);
            symbolno++; 
        }
        else {
            error = 1;
            sprintf(errorm,"Redeclared variable %s",yystack.l_mark[-3].string);
        }
      	yyval.f_val = 0.1;
    }
break;
case 54:
#line 390 "compiler_hw2.y"
	{

       /* dump = 1;*/
	    yyval.f_val = 0.1;
    }
break;
case 55:
#line 395 "compiler_hw2.y"
	{
       /* dump = 1;*/
	    yyval.f_val = 0.1;
    }
break;
case 56:
#line 402 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 57:
#line 405 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 58:
#line 408 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 59:
#line 414 "compiler_hw2.y"
	{
       /* dump = 1;*/
    }
break;
case 60:
#line 420 "compiler_hw2.y"
	{
        /*dump = 1;*/
    }
break;
case 61:
#line 423 "compiler_hw2.y"
	{
       /* dump = 1;*/
    }
break;
case 62:
#line 429 "compiler_hw2.y"
	{
	yyval.f_val = 0.1;
    }
break;
case 63:
#line 435 "compiler_hw2.y"
	{
	    if(yystack.l_mark[-2].f_val == yystack.l_mark[0].f_val) yyval.f_val = 1;
	    else yyval.f_val = 0;
    }
break;
case 64:
#line 439 "compiler_hw2.y"
	{
	    if(yystack.l_mark[-2].f_val >= yystack.l_mark[0].f_val) yyval.f_val = 1;
    	else yyval.f_val = 0;
    }
break;
case 65:
#line 443 "compiler_hw2.y"
	{
    	if(yystack.l_mark[-2].f_val <= yystack.l_mark[0].f_val) yyval.f_val = 1;
    	else yyval.f_val = 0;
    }
break;
case 66:
#line 447 "compiler_hw2.y"
	{
    	if(yystack.l_mark[-2].f_val != yystack.l_mark[0].f_val) yyval.f_val = 1;
    	else yyval.f_val = 0;
    }
break;
case 67:
#line 451 "compiler_hw2.y"
	{
    	if(yystack.l_mark[-2].f_val > yystack.l_mark[0].f_val) yyval.f_val = 1;
    	else yyval.f_val = 0;
    }
break;
case 68:
#line 455 "compiler_hw2.y"
	{
    	if(yystack.l_mark[-2].f_val < yystack.l_mark[0].f_val) yyval.f_val = 1;
    	else yyval.f_val = 0;
    }
break;
case 69:
#line 459 "compiler_hw2.y"
	{
	    yyval.f_val = 0.1;
    }
break;
case 70:
#line 465 "compiler_hw2.y"
	{ yyval.f_val = yystack.l_mark[-2].f_val + yystack.l_mark[0].f_val; }
break;
case 71:
#line 466 "compiler_hw2.y"
	{ yyval.f_val = yystack.l_mark[-2].f_val - yystack.l_mark[0].f_val; }
break;
case 72:
#line 467 "compiler_hw2.y"
	{
    	yyval.f_val = 0.1; 
    }
break;
case 73:
#line 473 "compiler_hw2.y"
	{ yyval.f_val = yystack.l_mark[-2].f_val * yystack.l_mark[0].f_val; }
break;
case 74:
#line 474 "compiler_hw2.y"
	{ yyval.f_val = yystack.l_mark[-2].f_val / yystack.l_mark[0].f_val; }
break;
case 75:
#line 475 "compiler_hw2.y"
	{ 
/*	if(float_flag == 1){*/
/*	  printf("error");*/
 	      yyval.f_val = 0.1;
/*	}*/
/*	else	*/
/*	  $$ = (int)$1 % (int)$3; */
    }
break;
case 76:
#line 483 "compiler_hw2.y"
	{ 
    	yyval.f_val = 0.1; 
    }
break;
case 77:
#line 489 "compiler_hw2.y"
	{ yyval.f_val = yyval.f_val + 1; }
break;
case 78:
#line 490 "compiler_hw2.y"
	{ yyval.f_val = yyval.f_val - 1; }
break;
case 79:
#line 491 "compiler_hw2.y"
	{ 
	    yyval.f_val = 0.1; 
    }
break;
case 80:
#line 497 "compiler_hw2.y"
	{ yyval.f_val = yystack.l_mark[-1].f_val; }
break;
case 81:
#line 498 "compiler_hw2.y"
	{         
        if(lookup_symbol(symbol_table,yystack.l_mark[0].string,symbolno,now_scope,0)==0){
            error = 1;
            sprintf(errorm,"Undeclared variable %s",yystack.l_mark[0].string);
        }       
        yyval.f_val = 0.3; 
    }
break;
case 82:
#line 505 "compiler_hw2.y"
	{ yyval.f_val = 0.1; }
break;
case 83:
#line 506 "compiler_hw2.y"
	{ yyval.f_val = 0.2; }
break;
case 84:
#line 507 "compiler_hw2.y"
	{ yyval.f_val = 0.1; }
break;
case 85:
#line 511 "compiler_hw2.y"
	{         
        if(lookup_symbol(symbol_table,yystack.l_mark[0].string,symbolno,now_scope,0)==0){
            error = 1;
            sprintf(errorm,"Undeclared variable %s",yystack.l_mark[0].string);
        }
        yyval.string = yystack.l_mark[0].string;
    }
break;
case 86:
#line 521 "compiler_hw2.y"
	{ 
        if(lookup_symbol(symbol_table,yystack.l_mark[-2].string,symbolno,now_scope,0)==0){
            error = 1;
            sprintf(errorm,"Undeclared variable %s",yystack.l_mark[-2].string);
        }       
        yyval.f_val = 0.1; 
    }
break;
case 87:
#line 528 "compiler_hw2.y"
	{ 
        yyval.f_val = 0.1;
    }
break;
case 88:
#line 534 "compiler_hw2.y"
	{ yyval.f_val = 0.1; }
break;
case 89:
#line 535 "compiler_hw2.y"
	{ 
	    yyval.f_val = 0.1; 
	    float_flag = 1;
    }
break;
case 90:
#line 539 "compiler_hw2.y"
	{ yyval.f_val = 0.1; }
break;
case 91:
#line 544 "compiler_hw2.y"
	{ yyval.string = yystack.l_mark[0].string; }
break;
case 92:
#line 545 "compiler_hw2.y"
	{ yyval.string = yystack.l_mark[0].string; }
break;
case 93:
#line 546 "compiler_hw2.y"
	{ yyval.string = yystack.l_mark[0].string; }
break;
case 94:
#line 547 "compiler_hw2.y"
	{ yyval.string = yystack.l_mark[0].string; }
break;
case 95:
#line 548 "compiler_hw2.y"
	{ yyval.string = yystack.l_mark[0].string; }
break;
#line 1617 "y.tab.c"
    }
    yystack.s_mark -= yym;
    yystate = *yystack.s_mark;
    yystack.l_mark -= yym;
    yym = yylhs[yyn];
    if (yystate == 0 && yym == 0)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: after reduction, shifting from state 0 to\
 state %d\n", YYPREFIX, YYFINAL);
#endif
        yystate = YYFINAL;
        *++yystack.s_mark = YYFINAL;
        *++yystack.l_mark = yyval;
        if (yychar < 0)
        {
            if ((yychar = YYLEX) < 0) yychar = YYEOF;
#if YYDEBUG
            if (yydebug)
            {
                yys = yyname[YYTRANSLATE(yychar)];
                printf("%sdebug: state %d, reading %d (%s)\n",
                        YYPREFIX, YYFINAL, yychar, yys);
            }
#endif
        }
        if (yychar == YYEOF) goto yyaccept;
        goto yyloop;
    }
    if ((yyn = yygindex[yym]) && (yyn += yystate) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yystate)
        yystate = yytable[yyn];
    else
        yystate = yydgoto[yym];
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: after reduction, shifting from state %d \
to state %d\n", YYPREFIX, *yystack.s_mark, yystate);
#endif
    if (yystack.s_mark >= yystack.s_last && yygrowstack(&yystack) == YYENOMEM)
    {
        goto yyoverflow;
    }
    *++yystack.s_mark = (YYINT) yystate;
    *++yystack.l_mark = yyval;
    goto yyloop;

yyoverflow:
    YYERROR_CALL("yacc stack overflow");

yyabort:
    yyfreestack(&yystack);
    return (1);

yyaccept:
    yyfreestack(&yystack);
    return (0);
}
